import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {institutionAdminService as api} from '../../services/institutionAdminService'
import ImportHistoryTable from './components/ImportHistoryTable'
import {Field, PageHeader, Pager, QueryState} from './components/Shared'
import './InstitutionMaster.css'
export default function ImportHistoryPage() {
  const [page, setPage] = useState(0), [country, setCountry] = useState(''), [source, setSource] = useState(''), [status, setStatus] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState('')
  const query = useQuery({queryKey: ['institution-history', page, country, source, status, from, to], queryFn: () => api.history(page, {countryId: country, sourceId: source, status, dateFrom: from, dateTo: to})}), sources = useQuery({queryKey: ['institution-sources', ''], queryFn: () => api.sources()}), countries = useQuery({queryKey: ['institution-countries'], queryFn: api.countries})
  const rows = query.data?.content ?? []
  return <div className="im"><PageHeader title="Import History" description="Review past imports and resume work in progress."/><QueryState pending={countries.isPending || sources.isPending} error={countries.error || sources.error} retry={() => {void countries.refetch(); void sources.refetch()}}/><div className="panel im-section"><div className="im-filters"><Field label="Country"><select value={country} onChange={e => {setPage(0); setCountry(e.target.value); setSource('')}}><option value="">All Countries</option>{countries.data?.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Source"><select value={source} onChange={e => {setPage(0); setSource(e.target.value)}}><option value="">All Sources</option>{sources.data?.filter(row => !country || String(row.countryId) === country).map(row => <option key={row.id} value={row.id}>{row.sourceName}</option>)}</select></Field><Field label="Status"><select value={status} onChange={e => {setPage(0); setStatus(e.target.value)}}><option value="">All</option>{['CREATED','UPLOADED','PROCESSING','VALIDATION_COMPLETED','READY_FOR_REVIEW','IMPORTING','COMPLETED','FAILED','CANCELLED'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="From"><input type="date" value={from} max={to || undefined} onChange={e => {setPage(0); setFrom(e.target.value)}}/></Field><Field label="To"><input type="date" value={to} min={from || undefined} onChange={e => {setPage(0); setTo(e.target.value)}}/></Field></div></div><QueryState pending={query.isPending} error={query.error} retry={query.refetch}/>{query.data && <div className="panel"><ImportHistoryTable rows={rows}/><Pager data={query.data} page={page} change={setPage}/></div>}</div>
}
