import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {institutionAdminService as api} from '../../../../services/institutionAdminService'
import {Details, Field, QueryState, SafeLink} from '../Shared'
export default function ImportSourceStep({busy, canImport, submit}: {busy: boolean; canImport: boolean; submit: (country: number, source: number, version: string, type: string) => void}) {
  const [country, setCountry] = useState(''), [source, setSource] = useState(''), [version, setVersion] = useState(''), [type, setType] = useState('FULL')
  const countries = useQuery({queryKey: ['institution-countries'], queryFn: api.countries}), sources = useQuery({queryKey: ['institution-sources', country], queryFn: () => api.sources(country), enabled: !!country})
  const selected = sources.data?.find(row => String(row.id) === source && row.active && String(row.countryId) === country)
  return <form onSubmit={e => {e.preventDefault(); if (selected && version.trim() && canImport && !busy) submit(Number(country), Number(source), version.trim(), type)}}><h2>New Institution Import</h2><QueryState pending={countries.isPending} error={countries.error} retry={countries.refetch}/><div className="im-filters"><Field label="Country"><select required value={country} disabled={busy} onChange={e => {setCountry(e.target.value); setSource('')}}><option value="">Select country</option>{countries.data?.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Source"><select required disabled={!country || sources.isFetching || busy} value={source} onChange={e => setSource(e.target.value)}><option value="">Select source</option>{sources.data?.filter(row => row.active).map(row => <option key={row.id} value={row.id}>{row.sourceName}</option>)}</select></Field><Field label="Version"><input required maxLength={100} value={version} disabled={busy} onChange={e => setVersion(e.target.value)} placeholder="2026.1"/></Field></div>{country && <QueryState pending={sources.isPending} error={sources.error} retry={sources.refetch}/>}<fieldset disabled={busy}><legend>Import Type</legend>{['FULL','INCREMENTAL'].map(value => <label key={value}><input type="radio" name="import-type" checked={type === value} onChange={() => setType(value)}/>{value === 'FULL' ? 'Full Import' : 'Incremental Import'} </label>)}</fieldset>{selected && <><Details values={{'Source Type': selected.sourceType, Description: selected.description}}/><SafeLink url={selected.sourceUrl}/></>}<div className="im-actions"><button className="primary" disabled={busy || !canImport || !selected || !version.trim()}>{busy ? 'Creating…' : 'Continue →'}</button></div></form>
}
