-- Phase 2 maintenance-master schema for PostgreSQL. Safe to run repeatedly.
-- The former shared delivery_mode master is intentionally removed. Event and
-- training delivery modes have independent maintenance tables.
DROP TABLE IF EXISTS public.delivery_mode;

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['event_delivery_mode','training_delivery_mode','event_type','training_type','opportunity_type','organization_type'] LOOP
    EXECUTE format('CREATE TABLE IF NOT EXISTS public.%I (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code VARCHAR(50) NOT NULL,
      name VARCHAR(100) NOT NULL,
      description VARCHAR(500),
      display_order INTEGER NOT NULL DEFAULT 0,
      active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT %I UNIQUE (code)
    )', table_name, 'uk_' || table_name || '_code');
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I(active)', 'idx_' || table_name || '_active', table_name);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP', table_name);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP', table_name);
    EXECUTE format('UPDATE public.%I SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL', table_name);
    EXECUTE format('UPDATE public.%I SET updated_at = created_at WHERE updated_at IS NULL', table_name);
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_' || table_name || '_code') THEN
      EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I UNIQUE (code)',
          table_name, 'uk_' || table_name || '_code');
    END IF;
  END LOOP;
END $$;
