-- Phase 1 master schema for PostgreSQL. Safe to run repeatedly.
-- Run before phase1-master-seed.sql.

CREATE TABLE IF NOT EXISTS public.country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(3) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone_code VARCHAR(5),
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_country_code UNIQUE (code),
    CONSTRAINT uk_country_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_state_country FOREIGN KEY (country_id) REFERENCES public.country(id) ON DELETE RESTRICT,
    CONSTRAINT uk_state_country_code UNIQUE (country_id, code),
    CONSTRAINT uk_state_country_name UNIQUE (country_id, name)
);

CREATE TABLE IF NOT EXISTS public.district (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id BIGINT NOT NULL,
    code VARCHAR(20),
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_district_state FOREIGN KEY (state_id) REFERENCES public.state(id) ON DELETE RESTRICT,
    CONSTRAINT uk_district_state_name UNIQUE (state_id, name)
);

CREATE TABLE IF NOT EXISTS public.city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id BIGINT NOT NULL,
    code VARCHAR(20),
    name VARCHAR(100) NOT NULL,
    postal_code VARCHAR(10),
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_city_district FOREIGN KEY (district_id) REFERENCES public.district(id) ON DELETE RESTRICT,
    CONSTRAINT uk_city_district_name UNIQUE (district_id, name)
);

CREATE TABLE IF NOT EXISTS public.language (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100),
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_language_code UNIQUE (code),
    CONSTRAINT uk_language_name UNIQUE (name)
);

-- Also install foreign keys when Hibernate created the tables before this
-- script was first run. PostgreSQL has no ADD CONSTRAINT IF NOT EXISTS.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_state_country') THEN
        ALTER TABLE public.state ADD CONSTRAINT fk_state_country
            FOREIGN KEY (country_id) REFERENCES public.country(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_district_state') THEN
        ALTER TABLE public.district ADD CONSTRAINT fk_district_state
            FOREIGN KEY (state_id) REFERENCES public.state(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_city_district') THEN
        ALTER TABLE public.city ADD CONSTRAINT fk_city_district
            FOREIGN KEY (district_id) REFERENCES public.district(id) ON DELETE RESTRICT;
    END IF;
END $$;

-- Hibernate can create timestamp columns without database defaults. Repair
-- pre-existing tables so manual inserts and imports behave like fresh tables.
ALTER TABLE public.country ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.country ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.state ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.state ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.district ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.district ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.city ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.city ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.language ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.language ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

UPDATE public.country SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE public.country SET updated_at = created_at WHERE updated_at IS NULL;
UPDATE public.state SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE public.state SET updated_at = created_at WHERE updated_at IS NULL;
UPDATE public.district SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE public.district SET updated_at = created_at WHERE updated_at IS NULL;
UPDATE public.city SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE public.city SET updated_at = created_at WHERE updated_at IS NULL;
UPDATE public.language SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE public.language SET updated_at = created_at WHERE updated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_state_country_id ON public.state(country_id);
CREATE INDEX IF NOT EXISTS idx_district_state_id ON public.district(state_id);
CREATE INDEX IF NOT EXISTS idx_city_district_id ON public.city(district_id);
CREATE INDEX IF NOT EXISTS idx_country_active ON public.country(active);
CREATE INDEX IF NOT EXISTS idx_state_active ON public.state(active);
CREATE INDEX IF NOT EXISTS idx_district_active ON public.district(active);
CREATE INDEX IF NOT EXISTS idx_city_active ON public.city(active);
CREATE INDEX IF NOT EXISTS idx_language_active ON public.language(active);
