import {useState} from 'react'
import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query'
import {institutionAdminService as api} from '../../../../services/institutionAdminService'
import type {DuplicateMatch} from '../../../../types/institution'
import {useAdminPermissions} from '../../../../hooks/useAdminPermissions'
import {useSnackbar} from '../../../../hooks/useSnackbar'
import {Badge, Confirmation, Details, Notice, QueryState} from '../Shared'
import {groupMatches, unresolvedRecords} from '../../workflow'

export default function DuplicateReview({importId, readOnly = false}: {importId: number; readOnly?: boolean}) {
  const query = useQuery({queryKey: ['institution-duplicates', importId], queryFn: () => api.duplicates(importId)}), client = useQueryClient(), {show} = useSnackbar(), {canManage} = useAdminPermissions()
  const [confirmation, setConfirmation] = useState<{match: DuplicateMatch; action: 'merge' | 'keep-separate'} | null>(null)
  const mutation = useMutation({mutationFn: ({match, action}: {match: DuplicateMatch; action: 'merge' | 'keep-separate'}) => api.resolve(importId, match.id, action), onSuccess: async () => {setConfirmation(null); show('Duplicate decision saved.'); await Promise.all([client.invalidateQueries({queryKey: ['institution-duplicates', importId]}), client.invalidateQueries({queryKey: ['institution-records', importId]}), client.invalidateQueries({queryKey: ['institution-summary', importId]})])}, onError: (error: Error) => show(error.message, 'error')})
  const groups = groupMatches(query.data ?? [])
  return <section><h2>Duplicate Review</h2><QueryState pending={query.isPending} error={query.error} retry={query.refetch}/>{query.data && <Notice>{unresolvedRecords(query.data)} duplicate records require review.</Notice>}{[...groups.entries()].map(([recordId, matches]) => <DuplicateGroup key={recordId} importId={importId} recordId={recordId} matches={matches} disabled={readOnly || !canManage || mutation.isPending} decide={(match, action) => setConfirmation({match, action})}/>)}{query.data?.length === 0 && <p>No duplicate candidates found.</p>}{confirmation && <Confirmation title={confirmation.action === 'merge' ? 'Merge with this institution?' : 'Keep this record separate?'} busy={mutation.isPending} close={() => setConfirmation(null)} confirm={() => mutation.mutate(confirmation)}>{confirmation.action === 'merge' ? 'This selects the existing institution for this incoming record. The decision will take effect when you apply the import.' : 'This marks the incoming record as a new institution when the import is applied.'}</Confirmation>}</section>
}
function DuplicateGroup({importId, recordId, matches, disabled, decide}: {importId: number; recordId: number; matches: DuplicateMatch[]; disabled: boolean; decide: (match: DuplicateMatch, action: 'merge' | 'keep-separate') => void}) {
  const [selected, setSelected] = useState(matches[0].id), match = matches.find(row => row.id === selected) || matches[0], resolved = matches.find(row => ['MERGED','KEPT_SEPARATE'].includes(row.resolution))
  const incoming = useQuery({queryKey: ['institution-record', importId, recordId], queryFn: () => api.record(importId, recordId), enabled: !match.importRecord})
  const existing = useQuery({queryKey: ['institution', match.institutionId], queryFn: () => api.institution(match.institutionId), enabled: !match.institution})
  const record = match.importRecord || incoming.data, institution = match.institution || existing.data
  return <article className="panel im-section"><h3>Possible Duplicate · Row {record?.rowNumber ?? recordId}</h3>{resolved ? <Badge value={resolved.resolution}/> : <p>Select the correct candidate, or keep the incoming record separate.</p>}<label className="im-field">Candidate institution<select value={selected} disabled={!!resolved || disabled} onChange={e => setSelected(Number(e.target.value))}>{matches.map(candidate => <option value={candidate.id} key={candidate.id}>{candidate.institution?.name || `Institution #${candidate.institutionId}`} · {candidate.matchScore}%</option>)}</select></label><QueryState pending={(!match.importRecord && incoming.isPending) || (!match.institution && existing.isPending)} error={incoming.error || existing.error} retry={() => {void incoming.refetch(); void existing.refetch()}}/><div className="im-compare"><section><h4>Incoming Record</h4><Details values={Object.fromEntries(Object.entries(record?.normalizedData || record?.mappedData || {}).filter(([key]) => ['name','city','administrativeArea','country','website'].includes(key)))}/></section><section><h4>Existing Institution</h4><Details values={{Name: institution?.name, City: institution?.city?.name || institution?.cityName, 'Administrative Area': institution?.administrativeArea?.name, Country: institution?.country?.name, Website: institution?.website}}/></section></div><p><strong>Match score: {match.matchScore}%</strong></p>{match.matchReason ? <Details values={match.matchReason}/> : <p>Score breakdown not provided.</p>}{!resolved && <div className="im-actions"><button disabled={disabled || !record || !institution} onClick={() => decide(match, 'merge')}>Merge</button><button disabled={disabled || !record} onClick={() => decide(match, 'keep-separate')}>Keep Separate</button><button disabled title="Ignoring duplicates is not available">Ignore</button></div>}</article>
}
