import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {institutionAdminService as api} from '../../../../services/institutionAdminService'
import type {Classification, ImportRecord} from '../../../../types/institution'
import {Badge, Details, Dialog, Field, Notice, Pager, QueryState} from '../Shared'
import {display} from '../formatting'
const tabs: [Classification, string][] = [['','All'],['NEW','New'],['UPDATE','Updated'],['UNCHANGED','Unchanged'],['DUPLICATE','Duplicates'],['ERROR','Errors']]
export default function ImportRecordsTable({importId, initial = ''}: {importId: number; initial?: Classification}) {
  const [classification, setClassification] = useState<Classification>(initial), [page, setPage] = useState(0), [search, setSearch] = useState(''), [selected, setSelected] = useState<number | null>(null)
  const query = useQuery({queryKey: ['institution-records', importId, classification, page], queryFn: () => api.records(importId, page, classification)})
  const rows = (query.data?.content ?? []).filter(row => JSON.stringify(row.normalizedData || row.mappedData || {}).toLowerCase().includes(search.toLowerCase()) || row.sourceIdentifier?.toLowerCase().includes(search.toLowerCase()))
  return <section><div className="im-tabs" role="group" aria-label="Record classifications">{tabs.map(([value, label]) => <button aria-pressed={classification === value} key={value} onClick={() => {setClassification(value); setPage(0)}}>{label}</button>)}</div><Field label="Search records on this page"><input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Name, city or source identifier"/></Field><QueryState pending={query.isPending} error={query.error} retry={query.refetch}/>{query.data && <><div className="tablewrap"><table className="im-table"><thead><tr>{['Row','Source ID','Institution Name','Country','City','Action','Confidence','Status','Details'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row => { const data = row.normalizedData || row.mappedData || {}; return <tr key={row.id}><td data-label="Row">{row.rowNumber ?? row.rowIndex}</td><td data-label="Source ID">{row.sourceIdentifier || '—'}</td><td data-label="Institution Name">{display(data.name)}</td><td data-label="Country">{display(data.country)}</td><td data-label="City">{display(data.city)}</td><td data-label="Action"><Badge value={row.action || row.classification}/></td><td data-label="Confidence">{row.matchConfidence == null ? '—' : `${row.matchConfidence}%`}</td><td data-label="Status"><Badge value={row.processingStatus || row.validationStatus}/>{row.errorMessage && <small className="im-error">{row.errorMessage}</small>}</td><td data-label="Details"><button onClick={() => setSelected(row.id)}>View Details</button></td></tr> })}{!rows.length && <tr><td colSpan={9}>No matching records on this page.</td></tr>}</tbody></table></div><Pager data={query.data} page={page} change={setPage}/></>}{selected !== null && <RecordDetails importId={importId} recordId={selected} close={() => setSelected(null)}/>}</section>
}
function RecordDetails({importId, recordId, close}: {importId: number; recordId: number; close: () => void}) { const query = useQuery({queryKey: ['institution-record', importId, recordId], queryFn: () => api.record(importId, recordId)}); return <Dialog title="Import Record Details" close={close}><QueryState pending={query.isPending} error={query.error} retry={query.refetch}/>{query.data && <RecordComparison row={query.data}/>}</Dialog> }
export function RecordComparison({row}: {row: ImportRecord}) {
  const target = row.institutionId || row.targetInstitutionId, action = row.action || row.classification
  const query = useQuery({queryKey: ['institution', target], queryFn: () => api.institution(target!), enabled: !!target && !row.institution && action === 'UPDATE'})
  const incoming = row.normalizedData || row.mappedData || {}, existing = row.institution || query.data
  return <><Details values={{Row: row.rowNumber ?? row.rowIndex, 'Source ID': row.sourceIdentifier, Action: action, Status: row.processingStatus || row.validationStatus}}/>{(row.errorMessage || row.validationErrors?.length) && <p role="alert" className="im-error">{row.errorMessage || row.validationErrors?.join('; ')}</p>}{action === 'UPDATE' ? <><QueryState pending={!!target && !row.institution && query.isPending} error={query.error} retry={query.refetch}/>{!existing && !query.isPending && <Notice>Existing institution values are unavailable.</Notice>}<table className="im-table"><thead><tr><th>Field</th><th>Existing</th><th>Incoming</th></tr></thead><tbody>{Object.entries(incoming).map(([key, value]) => {const old = existing ? (existing as unknown as Record<string, unknown>)[key] : undefined; const changed = !!existing && JSON.stringify(old) !== JSON.stringify(value); return <tr className={changed ? 'im-changed' : ''} key={key}><td data-label="Field">{key}{changed ? ' (changed)' : ''}</td><td data-label="Existing">{display(old)}</td><td data-label="Incoming">{display(value)}</td></tr>})}</tbody></table></> : <Details values={incoming}/>}<details><summary>Source Data</summary><pre>{JSON.stringify(row.rawData || {}, null, 2)}</pre></details></>
}
