import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {institutionAdminService as api} from '../../services/institutionAdminService'
import type {InstitutionSource} from '../../types/institution'
import {Badge, Details, Dialog, Field, Notice, PageHeader, QueryState, SafeLink} from './components/Shared'
import {date} from './components/formatting'
import './InstitutionMaster.css'
export default function InstitutionSourcesPage() {
  const [country, setCountry] = useState(''), [selected, setSelected] = useState<InstitutionSource | null>(null)
  const countries = useQuery({queryKey: ['institution-countries'], queryFn: api.countries}), query = useQuery({queryKey: ['institution-sources', country], queryFn: () => api.sources(country)})
  return <div className="im"><PageHeader title="Institution Sources" description="Trusted sources by country. Source management is read-only."/><QueryState pending={countries.isPending} error={countries.error} retry={countries.refetch}/><Field label="Country"><select value={country} onChange={e => setCountry(e.target.value)}><option value="">All Countries</option>{countries.data?.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><QueryState pending={query.isPending} error={query.error} retry={query.refetch}/>{query.data && <div className="panel tablewrap"><table className="im-table"><thead><tr>{['Country','Source','Source Type','Import Method','Priority','Status','Last Import'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{query.data.map(row => <tr key={row.id}><td data-label="Country">{row.country?.name || countries.data?.find(c => c.id === row.countryId)?.name}</td><td data-label="Source"><button className="im-link" onClick={() => setSelected(row)}>{row.sourceName}</button></td><td data-label="Source Type">{row.sourceType}</td><td data-label="Import Method">{row.importMethod?.replaceAll('_', ' ')}</td><td data-label="Priority">{row.priority}</td><td data-label="Status"><Badge value={row.active ? 'ACTIVE' : 'INACTIVE'}/></td><td data-label="Last Import">{row.lastImportAt ? date(row.lastImportAt) : 'Not provided'}</td></tr>)}{!query.data.length && <tr><td colSpan={7}>No sources configured for this country.</td></tr>}</tbody></table></div>}{selected && <Dialog title={selected.sourceName} close={() => setSelected(null)}><Details values={{Country: selected.country?.name || countries.data?.find(c => c.id === selected.countryId)?.name, 'Source Type': selected.sourceType, Description: selected.description, 'Import Method': selected.importMethod, Priority: selected.priority, Status: selected.active ? 'Active' : 'Inactive'}}/><SafeLink url={selected.sourceUrl}/><Notice>Contact your administrator to change source configuration.</Notice></Dialog>}</div>
}
